module.exports = {
  users: () => [
    {
      id: 1,
      name: "Rosco",
      lasName: "Faltskog",
      age: "12",
      email: "rfaltskog0@narod.ru",
    },
    {
      id: 2,
      name: "Fancie",
      lasName: "Beceril",
      age: "34",
      email: "fbeceril1@engadget.com",
    },
    {
      id: 3,
      name: "Skippie",
      lasName: "Gubbin",
      age: "31",
      email: "sgubbin2@ft.com",
    },
    {
      id: 4,
      name: "Rozele",
      lasName: "Orford",
      age: "41",
      email: "rorford3@state.gov",
    },
    {
      id: 5,
      name: "Hubie",
      lasName: "Scryne",
      age: "52",
      email: "hscryne4@weather.com",
    },
    {
      id: 6,
      name: "Fey",
      lasName: "Capel",
      age: "61",
      email: "fcapel5@nsw.gov.au",
    },
    {
      id: 7,
      name: "Romy",
      lasName: "Heppner",
      age: "71",
      email: "rheppner6@example.com",
    },
    {
      id: 8,
      name: "Leodora",
      lasName: "Philipsen",
      age: "82",
      email: "lphilipsen7@economist.com",
    },
    {
      id: 9,
      name: "Petronia",
      lasName: "Josifovitz",
      age: "92",
      email: "pjosifovitz8@google.com.hk",
    },
    {
      id: 10,
      name: "Revkah",
      lasName: "Lente",
      age: "17",
      email: "rlente9@wix.com",
    },
  ],
};
